### ISSUE TITLE
Avoid generating database writes on login view

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-server#1037]
Currently a bot sees a link in the header to `/login/github/?next=/` and clicks that link which triggers the auth flow. 

This flow creates a session in the database, which is bad.

Change the button so that it uses a `POST`. I'm not sure if this will Just Work, or if we'll have to intercept the click and turn it into a `GET`.

If it's easy, for bonus points, we've agreed a nice UX would be to move the login button to its own page where the button says "Sign in with Github" (perhaps also a "Register with Github" which actually goes to the same place, just to make it less confusing)

**Comment by sebbacon** [comment]
https://github.com/omab/django-social-auth/blob/master/social_auth/views.py#L22-L24 is the view that gets called -- either posting to that just works, or there's one line to copy

```py
@strategy('socialauth_complete', load_strategy=load_strategy)
def auth(request, backend):
    return do_auth(request.strategy, redirect_name=REDIRECT_FIELD_NAME)

```

**Comment by sebbacon** [comment]
So I think this should be as "simple" as:

* Apply a `require_POST` decorator to the `auth` view mentioned above, via urls.py
* make the login "link" a form button, styled to look as it does currently (`btn btn-link` should do it IIRC)
* change the "login" link in the header to take you to a dedicated page with two buttons with identical targets, one for "register"
 and the other for "login"

**Comment by evansd** [comment]
There are three things we need to do here:
1. Make the above view accept POSTs
2. Stop the above view from accepting GETs
3. Make clicking the login button send a POST rather than a GET

To make any changes to the view behaviour we need to handle the URL ourselves. Currently we just delegate to social-auth here:
https://github.com/opensafely-core/job-server/blob/20475e8d2fa0e33d9f32e0b13210e5a0d2a657b5/jobserver/urls.py#L250

I think we'll need to add a URL pattern above here which matches the login request and sends it elsewhere. Here's the social auth URL we're attempting to override:
https://github.com/omab/django-social-auth/blob/699571a3b6d84aa2c25ffce59daa4c7f3559a0e4/social_auth/urls.py#L13

We can hopefully achieve all the behaviour changes we need with view decorators.

To make the view accept posts we need to remove the default CSRF protection it has. (The behaviour we're exposing was previously accessible via a GET, so there's no additional expose here.). This can be done using the `csrf_exempt` decorator.

To reject GETs we can just use the `require_POST` decorator, as mentioned above.

To make clicking login send a POST we can change the links to a form button. There are two login links in the templates which you can find by searching for `social:begin`. You'll need to change the `<a href=...>...</a>` tags to forms like so:
```html+django
<form method="POST" action="{% url "social:begin" "github" %}?next={{ request.path }}">
  <button class="btn btn-outline-light mt-2 mb-3 my-lg-0" type="submit">Login</button>
</form>
```

...

Profit?

**Comment by ghickman** [comment]
One thing to note, you'll need to put the new URL `path()` line before the social auth include because URLs are parsed top to bottom with the first match winning.

**Comment by iaindillingham** [comment]
The new login page.

![Screenshot 2021-10-05 at 10-56-28 OpenSAFELY Jobs](https://user-images.githubusercontent.com/477263/136001874-d3deb089-bd11-4114-9bd9-53148947aa1f.png)
