### ISSUE TITLE
Made a PDF (or similar) of the application form available

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/job-server#1203]
This looking great. One improvement for researchers/applicants is to make a format available where it can be downloaded or copied to a google doc. Two  use cases

> As a casual passerby researcher, I would like to see the whole form in s single place, to quickly assess if I wish to become an applicant

> As a applicant on behalf of  a large research group, I would like a version of the form that I can copy to a google doc so that we can collaboratively fill it in. I will then return to the form once my team is happy and copy the answers in

For the first use case, currently the form has mandated answers so a researcher can't even see the whole form without putting in fake answers! I suspect we'll end up with a lot of "test" applications just to see the questions!

On the second use case - we experience a lot of pain with this in funding applications. Generally someone on the team has to go through and online form or PDF and copy questions into a google doc before we can collaboratively edit!

**Comment by amirmehrkar** [comment]
I dont think you can see whole form on one page without answering something. 
Yes @brianmackenna would be helpful. 

Plus the download obviously for other purposes.

I will also potentially need to "amend" sections - and for now, i will have to create a google form for suggested changes occasionally. I dont see another way around that.

**Comment by ghickman** [comment]
These two tasks can probably be combined into 1 if we make the "whole form in one place" an intentional artefact of providing a PDF.

However, this is not a quick fix.  I see two options here:
1. generate a web view which is all the pages combined into a single, very long page, add a button to download as PDF (essentially print as PDF).
2. construct a PDF from the existing pages using something like wkhtmltopdf.

Neither of these is simple.

Constructing a single page will need work to the wizard class to make it work in unintended ways.  It's designed to work with a single item in the form_specs, because each item represents a page.  We might be able to create a wrapper to the Wizard class (Sorceror?) which iterated through each of them to build a single giant page, but it will need exploratory work to decide if that's possible and how much work.

My previous experiences of dynamically generating PDFs is not a positive one.

For either route I wonder if we're causing a different set of problems for users though.  How are they expecting to input the data collected with the PDF?  Manually copy it over to our application form on job-server?

**Comment by brianmackenna** [comment]
I think copy and paste is what people will expect (especially if we write this as the "download" button)

As another solution - is the form stable enough now that we could just make a word/pdf version manually? And host to be downloaded?

**Comment by ghickman** [comment]
> is the form stable enough now that we could just make a word/pdf version manually?

I don't think so based on tweaks I've seen from @amirmehrkar coming in.  Having a manually crafted option also means any change has to bear the weight of updating that manual form before we deploy.

**Comment by ghickman** [comment]
Fixed in #2755
