### ISSUE TITLE
Explain what cancelling a request/job does

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/job-server#1629]
I submit a request, containing actions A, B, C, and C depends on B depends on A. 

Job for A completes successfully. B is still running, and we decide we want to cancel B and change the script. But we want to keep the completed outputs from A. 

If we cancel B (big red button on the job page at `.../<project>/<workspace>/<request>/<job-id>`), then B is cancelled, C is cancelled (because it depends on B), but the status of A remains "success".

If we cancel the entire request (big red button on the request page at `.../<project>/<workspace>/<request>`), then A, B, and C are all cancelled. 

Can we:

* check that the above is true
* explain it more concisely and add the explanation somewhere near those big red buttons on each page

**Comment by ghickman** [comment]
The cancel button on a Job page adds the Job's action to a list on its JobRequest, while the cancel button on a JobRequest page adds the actions for every related Job to the same list.

We do no checking of a Job's status here since the list is considered a "request for cancellation", with job-runner being the final authority on how to handle that request.

However, the idea that cancelling a JobRequest marks successful jobs as cancelled/failed seems like a bug to me.

We should be able to add some explainer text around the buttons as well.

**Comment by sebbacon** [comment]
Anyone picking this up should discuss with Dococzar @StevenMaude

**Comment by rebkwok** [comment]
@StevenMaude A running job request has a page like this, listing all its component jobs:
![Screenshot from 2022-03-09 11-23-54](https://user-images.githubusercontent.com/6770950/157432375-75eb57cb-406c-4dd0-87c5-d8e97be791cf.png)

And the page for an individual running job looks like this:
![Screenshot from 2022-03-09 11-25-04](https://user-images.githubusercontent.com/6770950/157432647-564b3446-b064-4954-a750-7eec174f5d75.png)

I think that the "Cancel" button on the job request page is misleading - it's not cancelling the request at its current stage, it's marking all component jobs as failed.  I'd suggest that we relabel that button to "Reject request" or "Discard request", along with explanatory text something like: "Rejecting this request will mark all jobs in the request as cancelled, including any that have succeeded so far.  To cancel a job but keep outputs from other completed jobs in this request, select and cancel the individual running job instead."

And on the individual job page, add explanatory text below the Cancel button: "Cancelling this job will cancel both the current job and any subsequent jobs that depend on it."

**Comment by evansd** [comment]
I think this is actually a bug (or at least a behaviour change) in job-runner introduced with all the refactoring work that was done last year. Previously, asking for an already completed job to be cancelled could never change it's state. But since [this PR](https://github.com/opensafely-core/job-runner/pull/295) that's no longer true.

I note this comment in the review from yours truly:
> I concur with your assertion that this is now 100% guaranteed to be correct and addresses all possible problems with the job-runner state.

I think we could fix this in job-runner _relatively_ easily if we wanted to. The change would be to ignore only failed jobs marked `cancelled`, not successful jobs.

An alternative (probably a better one) would be for the cancel button on job request to only cancel jobs which are still running (according to job-server). It would still be possible to cancel a completed job if you hit the button at just the wrong time, but I don't think that matters at all.

It would be a case of adding a filter to this list of `actions`:
https://github.com/opensafely-core/job-server/blob/49f780c824e339652c15ab2cbc60dbc01cadee31/jobserver/views/job_requests.py#L54-L55

**Comment by StevenMaude** [comment]
If the job request cancellation behaviour is unlikely to be fixed in the next couple of weeks, I think it's fine to at least document the current behaviour. @rebkwok's proposed wording looks good to me.

And, feel free to correct me, I *think* this clarification:

> And on the individual job page, add explanatory text below the Cancel button: "Cancelling this job will cancel both the current job and any subsequent jobs that depend on it."

might be useful as a reminder in either case.
