### ISSUE TITLE
SPIKE Can we automatically add users and repos to the relevant GitHub Team?

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#1905]
We'd like to reduce the amount of access researchers currently have to repos in the GitHub organisation. This will make housekeeping tasks easier for us and will improve security, as well as be reassuring to researchers that only people who are supposed to can write to their repos (currently all org members can write to all study repos).

The outcome should be that we don't need to manually manage teams for those that want this level of protection (currently just Bristol).

The value is:
1. Removal of maintain permissions on the repos from the Bristol/Cambridge group
2. Researchers will only be able to change repos in their GH team, so increased security/confidence in OpenSAFELY
3. ~Allow us to rely on the use of topics on repos within job-server, to identify repos that need action taken on them (i.e to be made public after a certain amount of time)~ this is already done, apart from the Bristol team having maitain permissions, which is covered by 1) above.
4. Increased security, as users will have fewer permissions by default

Questions:
1. ~Can we get job server to produce a json file of what the organisation should look like, to be consumed by the github-admin cronjob?~
2. Can we avoid giving ~the cronjob~ job-server access to GitHub that bypasses the need for a human w/GH account?
3. Do we need to upgrade to enterprise GH in order to do this properly?

**Comment by bloodearnest** [comment]
Fist part of this is get a big old list of orgs/users/workspaces in an API from job-server

**Comment by bloodearnest** [comment]
Had a look at this, and I thought it was an issue.

But I think it can still work.

The issue is this - we don't want /a compromised job-server to be able to add arbitrary GH users to trusted repos. This would bypass the separate GH security layer.

However, the cron job could be restricted to just adding/removing users to teams, not the org. They would have to be manually added to the org as per currently.

This allows an attacker to maybe move people around, but not to add arbitrary users.

**Comment by bloodearnest** [comment]
I have caputred this in more detail here https://docs.google.com/document/d/1NhiVIX18kgdGwQwZMmnGCPM06sWVKcsLHcnXHySkz0U/edit#
