### ISSUE TITLE
SPIKE: job-runner system metrics collection options for honeycomb

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-server#1954]
We need a generic way to collect metrics in a backend, and send them to job-server, and then on to honeycomb.

Currently, we derive job-runner metrics from the data it sends to job-server about job start/finish times.

We also want to collect:
 - general job cpu/memory usage
 - specific job metrics (e.g. cohortextractor db query times)
 - general host metrics(cpu/memory/disk)

We need:
a) a secure way to collect metrics for a specific job
b) a way to collect TPP VM metrics (possibly just honeycomb's host stuff)
d) a secure way to send these metrics up to job runner and then into honeycomb

**Comment by madwort** [comment]
["Honeycomb metrics"](https://www.honeycomb.io/metrics/) is the name for Honeycomb's host data collector stuff, so we might want to avoid using the word metrics for what we collect from the job-server/job-runner apps? They're events/spans with 1:1 mapping to occurrences on the server, and metrics would be aggregated numbers corresponding to the overall effect of multiple occurrences on the server.

**Comment by madwort** [comment]
We also touched on the idea of instrumenting job-runner directly and proxying the spans via job-server - instead of the current route of API calls to transfer information from job-runner to job-server and then instrumenting job-server. Maybe that's a seperate ticket? I think it's something that fairly far-off right now.
