### ISSUE TITLE
Spike on GH badges

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#1968]
Spike on using GH badges

### Background

- We only expect to spend a max of N hours on this exploratory work
- It would be very useful to have a way to link repo READMEs back to useful things (e.g. job server workspace page)
- Asking users to add links and remember to update things is prone to error
- We could use badges to add links dynamically and colour-coding to show state
- Could badges be used to incentivise other actions by researchers? (e.g. add link to published papers, etc)
- Could we also show published outputs, released outputs and number of jobs run? This would show how active a repo is and would help provide Amir with useful information.

### Acceptance criteria

- Notes have been made in google doc explaining what badges could be used for and how much effort would be involved in implementing this (possibly with different options, and a proposed best solution)
- There is a link to this doc from the “Make Amir’s Life Easier” doc https://docs.google.com/document/d/1N5XC0faHmfC_XxJiH3wSGsftfY402G3hc4ezDrO6nZ8/edit?usp=sharing
- The findings have been communicated to the rest of the pipeline team and Catherine

**Comment by ghickman** [comment]
There are 3 obvious and easy badges that I think have relevance for this:
* number of jobs for a workspace
* number of released files for a workspace
* number of published outputs for a workspace

These are all workspace specific but a given branch on a repo can only be tied to one workspace (we have a uniqueness constraint to enforce this) so I think keeping these workspace specific makes sense here.

We can't support "does this repo have a paper published" yet since we don't have that information tracked in the platform but it would be easier to add later on.

**Comment by ghickman** [comment]
Doc updated with some of the bits above and some thoughts on driving users to do take actions.
