### ISSUE TITLE
Provide indication of load times when viewing level 4 files

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#2106]
When viewing level 4 files on the server via the jobs site, it can take a while to load all the files if the workspace is large. It would be nice to indicate somewhere that this is expected for large workspaces, beyond having the loading bar.

Example workspace - https://jobs.opensafely.org/lshtm/70-lone-households-and-mental-health/lone_households/

**Comment by bloodearnest** [comment]
Interesting.

This is possibly because we calculate the hash of every file in the workspace, when we index it. when there are many it could take a while.

The reason we do this was for when a review request was submitted, we wanted to mach sure the file hadn't been updated under the user by job-runner whilst they we looking at the old version. It should be cached, but on first load it can be a hit.

I think we can probably avoid hashing the file when indexing the files, and instead hash it on demand when the user view the file? That actually would play nicely with adding `ETag` headers. It would allow us to get rid of the hash caching code, which is the cause of occasional bugs.

**Comment by lucyb** [comment]
This won't be needed once Airlock is in use.
