### ISSUE TITLE
Restrict access to SQL Runner to users who already have database access

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/job-server#2237]
From Catherine: Can someone update this Issue with a description of the new plan please? (see discussion below)...
And please include this extra bit of text: 
***This issue is the final piece of work required to tidy up the [SQL Runner initiative](https://docs.google.com/document/d/1gauAgyGaM8YDWpd7oVnd1pL8TIkY65sipPnQocg8IYU/edit?usp=sharing). Therefore, please do not de-prioritise it without first talking to the Product and Data teams. Thank you!***

_Original text from Peter below:_
A handful of Bennett Institute users (those who have signed contracts with NHSE) have direct access to data in OpenSAFELY backends, to inform the development of tools such as Cohort Extractor and Data Builder.

SQL Runner provides a way to run arbitrary SQL against an OpenSAFELY backend, as a job run via the Job Server.  This brings several benefits, including full audit logs and output checking.

However, until we have done further work to establish how SQL Runner fits into the OpenSAFELY IG framework, we should restrict access to SQL Runner to users who already have database access.

In practical terms, this means:

* creating a new authorization role: `SQLRunnerUser`
* before a `JobRequest` is created, check whether any of the actions in the `JobRequest` are for SQL Runner, and if so, whether the user has the `SQLRunnerUser` role
* assigning the `SQLRunnerUser` role to only Bennett Institute users who currently have direct access to data in OpenSAFELY backends

**Comment by iaindillingham** [comment]
I think that by "direct access" you mean L2 credentials. According to Amir's spreadsheet, this group also includes users who are not part of the Bennett Institute, but who nevertheless have been approved. I don't think we'd like to include these users; I think we'd like to restrict access to the group of users who have L2 credentials _and_ who are part of the Bennett Institute.[^1]

Whilst we could restrict access to the group of users who have L3 credentials ([ebmdatalab/kissh](https://github.com/ebmdatalab/kissh)), I don't think we want to because we'd like users from outside the Tech group to be able to use SQL Runner; for example, users from the Service Analytics group.

[^1]: That said, I'm unsure whether Amir's spreadsheet is accurate. (We recently reallocated L2 credentials.)

**Comment by bloodearnest** [comment]
This is not a trivial and clean thing do do, there are number of issues:

1) The information of who has level 2 access is not held by job-server currently - that's a list maintained by Amir/TPP.  So, we can create a `SQLRunnerUser` or similar, but it would an independent list and may drift over time. Possibly not a problem, and ideally job-server would be the source-of-truth for who should have level 2 access, but that work is not trivial.

2) job-server doesn't know at the point of JobRequest submission time whether a `sqlrunner job` will be run or not - only job-runner has the state to know this or not, and it doesn't know anything about user permissions.  The best job-server could do is detect if there are *any* `sqlrunner` actions or not, and block accordingly.

3) There a confusion between users, projects, and workspaces, and the separate between who can author code and who can run code.  If we allow SQLRunner users to run code on a project that non-SQLrunner users can author on, then we're not providing a robust control. The non-SQLrunner user could modify exisitng (or add a new sqlrunner action and make it a dependency) and the SQLrunner user could very easily run it without realising. 


Given the mess above, I propose:

a) Rather than linking permissions to *users* we should instead give the permission to *projects*, and then control who has `ProjectDeveloper` role in that project. So we could have a "Data Curation" project, and that project is allowed to run sqlrunner, with a set of Bennett users as `ProjectDeveloper`s

b) if job-server detects *any* sqlrunner actions in the project.yaml, it should not run it unless it is an approved projects, as per above.

That's not idea, but it's relatively simple to implement with the current system.

@ghickman may also have thoughts.

**Comment by ghickman** [comment]
We can't give permissions to projects, they always go to user, sometimes via an intermediary (typically this is a project).  If we were to use ProjectDeveloper then any user with that role could run `sqlrunner` on the project they had that role via.

The potential drift of who has L2 and has the potential `SQLRunnerUser` role is something we've seen before, in small doses, and I think the importance of what we're allowing here means it's something we want to be very wary of.  In an ideal future job-server will become the owner of that information but we're a way off from that now and I'm keen to avoid giving us yet more future data-clean-up tasks.

How about a middle ground:
* Project grows a boolean, something like `can_talk_directly_to_datastore` (datastore because I don't think spark/databricks are traditional "databases"? Please correct me if I have that wrong!)
  * This isn't the nicest solution but we can write a comment as to why it exists and migrate to using "user has L2 access" instead of this boolean if/when that data moves into job-server.
* `jobserver/pipeline_config.py` grows a `has_sqlrunner_action()` function which returns a boolean showing whether any action in a given pipeline config runs sqlrunner
* `JobRequestCreate.dispatch()` returns a 404/error state if the project.yaml has `sqlrunner` defined in an action AND NOT `project.can_talk_directly_to_datastore`.

We'll need to create a new project for this, I don't think OpenSAFELY Testing is the best place to put this if we're giving the whole project access to L2.  Something like `OpenSAFELY Data Curation`?  I think that still fits with [our platform policy on data curation](https://docs.opensafely.org/developer-access-policy/#data-curation-activities), but I'd be keen to get Amir's opinion on that to confirm.

This avoids job-runner having any context of the issue, and allows us to use the project membership of this new project to gate developer access.

**Comment by iaindillingham** [comment]
> We can't give permissions to projects, they always go to user, sometimes via an intermediary (typically this is a project). If we were to use ProjectDeveloper then any user with that role could run sqlrunner on the project they had that role via.

I misunderstood this on first reading. On second reading, I think these users would be able to execute an SQL Runner action on _any_ project, not just the (new) curation project. Is that the case?

Plus one for avoiding drift 👍🏻.

In my mind, all projects talk directly to the datastore in the sense that cohort-extractor and Data Builder actions are present in most projects; SQL Runner actions are present in some. Possibly we're distinguishing between whether a project allows user-written queries (SQL Runner) rather than something like stored procedures? (cohort-extractor, Data Builder) Rather than coupling the names of the properties/methods to SQL Runner, should we generalize them?

There's a clear distinction between testing and data curation in our [access policy for platform developers][1], so a similarly clear distinction in OS Jobs would be, well, clear 🙂. Plus one for a new data curation project 👍🏻.

[1]: https://docs.opensafely.org/developer-access-policy/

**Comment by ghickman** [comment]
> I think these users would be able to execute an SQL Runner action on any project, not just the (new) curation project

Yep, that's correct 👍

**Comment by bloodearnest** [comment]
> We can't give permissions to projects, they always go to user, sometimes via an intermediary (typically this is a project). If we were to use ProjectDeveloper then any user with that role could run `sqlrunner` on the project they had that role via.


Right, I mean permission in the broader sense, not in the `Permission` models at the moment, which is user-centric. But that's basically what your proposal is, so we're on the same page :)

For comparison, we already have project level permissions for restricted dataset access - they are not stored in job-server currently, but in opensafely-cli.

If/When project level access to datasets (Contracts) is formalised, this could be part of it.

If you squint, sqlrunner access is kinda like restricted dataset access, but with bells on.


> The potential drift of who has L2 and has the potential `SQLRunnerUser` role is something we've seen before, in small doses, and I think the importance of what we're allowing here means it's something we want to be very wary of. In an ideal future job-server will become the owner of that information but we're a way off from that now and I'm keen to avoid giving us yet more future data-clean-up tasks.
> 
> How about a middle ground:
> 
> * Project grows a boolean, something like `can_talk_directly_to_datastore` (datastore because I don't think spark/databricks are traditional "databases"? Please correct me if I have that wrong!)

How about 'privileged_db_access'?
   
>   * This isn't the nicest solution but we can write a comment as to why it exists and migrate to using "user has L2 access" instead of this boolean if/when that data moves into job-server.

I don't think this is directly related to the `user has l2` tracking - I suspect this *should* be project level rather than user level.


> * `jobserver/pipeline_config.py` grows a `has_sqlrunner_action()` function which returns a boolean showing whether any action in a given pipeline config runs sqlrunner

:+1: 

> * `JobRequestCreate.dispatch()` returns a 404/error state if the project.yaml has `sqlrunner` defined in an action AND NOT `project.can_talk_directly_to_datastore`.
> 
> We'll need to create a new project for this, I don't think OpenSAFELY Testing is the best place to put this if we're giving the whole project access to L2. Something like `OpenSAFELY Data Curation`? 

Yes, there may be multiple projects that need it, potentially. But they should be minimal and restricted. To the point that may be we don't have UI to set it, it needs a management command?

**Comment by ghickman** [comment]
Agreed on all points 👍🎉

**Comment by bloodearnest** [comment]
A proposed simplest possible implementation:

 - we add a flag allowing only certain projects to use sqlrunner
 - if a project.yaml contains *any* sqlrunner jobs, the containing project *must* have that 
   flag set, or else you cannot submit the job.

I think this is just:
 - 1 additional db column
 - an additional validation check and user message on the job submission page
