### ISSUE TITLE
Help IG team to identify when applications have been completed and submitted

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2381]
Request from Amir. NOTE: Catherine needs to report back to Amir on decision

Amir and Liam are struggling to identify applications that have been finished and submitted amongst all those that have been partially completed but not yet submitted. Is there a way to make this easier for them? 

Their suggestion: Implement a completed button on the application form, to gage when applicant has officially submitted their application in full

**Comment by ghickman** [comment]
The process of submitting an application should be tracked in some way then surfaced to the staff area, likely with a filter on the list page, to make it easy for Amir/Liam to filter applications down to just those.

**Comment by lucyb** [comment]
There's a "completed" status on the model and a filter on the[ list page in the staff area](https://jobs.opensafely.org/staff/applications/?status=completed) already. However, it doesn't seem to be used. 

What happens when someone presses "submit" at the end of the application process? Should that change the status to completed and make everything read only? It's not entirely clear to the user what happens when that button is pressed at the moment, especially since it doesn't seem to change the status.

**Comment by ghickman** [comment]
@lucyb – those statuses are for the IG team to change as they work through an application.  We could add a submitted one that's selected when a user submits their application.  It would be added to the staff area filter automatically too.

**Comment by lucyb** [comment]
Ah, okay. So the statuses would be Ongoing -> Submitted -> Competed -> Approved_* ?
