### ISSUE TITLE
Tie UI form into AnalysisRequestCreate page

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2492]
Integrate the form @tomodwyer has been building onto the AnalysisRequestCreate page.

We'll need to decide if it's going to submit via a JSON API or with form data, and based on that how we're doing to validate the incoming data, and return any errors to the form.

**Comment by lucyb** [comment]
The data that will need to be passed from the AnalysisRequest into the code that creates a git commit with all the analysis/report code in can be found in the params being passed into the report code at the moment over here:

https://github.com/opensafely/medication-reviews/blob/1576fbd74d2fe651a03ce7dbefb6004626430631/project.yaml#L245-L253

The codelist slugs and names will likely be used to download the relevant CSVs and added directly to the repo rather than passed into cohortextractor as parameters.

**Comment by ghickman** [comment]
@tomodwyer – do you know what format you'd like errors returned in?  Django's Form.errors is a list of HTML strings, which I suspect isn't of much use to us here but I can likely translate that into what you need.

**Comment by tomodwyer** [comment]
Ideally just a status code and text string would be fine. I can work with HTML strings if needs be.

**Comment by ghickman** [comment]
I think I can do you one better, I forgot that the string representation of `form.errors` is HTML, but it's actually a dict under the hood which we can access in the template with `{{ form.errors }}`.  Since we don't provide the form on a GET, but do on a failed POST we should be able to do something along the lines of:

```
{% if form %}
{{ form.errors|json_script:"errors" }}
{% endif %}
```

and then in the SPA div:

```
{% if form %} 
data-errors={{ errors }}
{% endif %}
```

**Comment by tomodwyer** [comment]
Perfect 👌 that works for me!

**Comment by lucyb** [comment]
Can this be considered done now?

**Comment by tomodwyer** [comment]
This is done 🚀
