### ISSUE TITLE
Integrate Louis' report code into form submission

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2498]
Louis has been working on the report code for v2.  Once he's at a point where he feels we can start integrating we should wire it into the AnalysisRequestCreate page.

We'll store the code as a template and interpolate in the values submitted by the form.

TBD: can we use simple values (eg `codelist_1=<slug from opencodelists>`) or do we need to generate larger snippets to handle the logic contained by the windowing functionality we now provide?

TBD: if we roll the functionality in #2494 into a new service do we keep the template and interpolation code in job-server or do we encapsulate in the external service?

**Comment by lucyb** [comment]
Note: this work is dependent on the outcome of https://github.com/opensafely-core/interactive.opensafely.org/issues/465. It may simplify the solution a lot if some/all of it was moved into Reusable Actions.

If not, another option may be to store the analysis/report code in a separate repo and clone it each time. That has some drawbacks though.

**Comment by lucyb** [comment]
The data that will need to be passed from the AnalysisRequest into the code that creates a git commit with all the analysis/report code in can be found in the params being passed into the report code at the moment over here:

https://github.com/opensafely/medication-reviews/blob/1576fbd74d2fe651a03ce7dbefb6004626430631/project.yaml#L245-L253

The codelist slugs and names will likely be used to download the relevant CSVs and added directly to the repo rather than passed into cohortextractor as parameters.

**Comment by lucyb** [comment]
If I understand correctly, this ticket should cover passing the necessary data from the form submission/analysis request creation into the module that generates a commit into the relevant repo (see https://github.com/opensafely-core/job-server/issues/2494)
