### ISSUE TITLE
SPIKE Understand how to publish Interactive Reports

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2540]
We've moved Interactive Reports into Job Server and can display unpublished reports using released outputs. However we need to understand how these reports will be published so they're available for viewing by the public.

Questions to answer
1. How are unpublished reports shared (is this a different spike?)
2. How does a researcher publish a report?
3. Can this workflow be used for Reports reports or is this likely to be specific to Interactive?

**Comment by ghickman** [comment]
After discussion with @CLStables and @LFISHER7 we think we've come up with publishing means on OpenSAFELY:

> Making something available to the public after NHSE has confirmed they are happy for it to be made public.

Where something is currently a released file or a report, although this could be expanded upon in the future.

---

Based on this I think we can make some changes to how we model this.

We still want to have the two step process of:
1. request to publish N files
2a. request is accepted and files are public
2b. request is denied (we don't really handle this currently but it can still technically happen)

but instead of having Snapshots handle both draft and published state we can model the request for publishing, gathering extra context around why these files, etc for internal/NHSE benefit, and then create a Snapshot if the request is success (and if we're clever about it we could maybe handle accepting a subset of a request).

The UI for this will likely be quite different from what we have now, and is out of scope for OSIv2, but OSIv2 still has the need to publish the files for a report so I think we can build the necessary underlying changes here and address the general publishing of files at a later date.

For OSI we can add:
* a model to capture "request to publish N files" (SnapshotRequest?)
* a model to capture "request to publish a report" (ReportRequest?)
* a page to capture the extra context necessary to publish a request
* tools in the staff area for the staff who will have to handle these requests (eg dashboard, assigning requests to users, etc)
* tools in the staff area to accept/deny a request to publish

The "request to publish a report" model and flow would hide that we're also requesting to publish the underlying file, much like we hide JobRequest and Workspace from an Interactive user, but would let us confirm that it's the flow we want.

It might be possible to introduce the "request to publish N files" model to the current publishing flow, without changing the UI but some exploratory work will need to be done.

---

To answer the specific questions:
1. expiring URLs, exposed to the user as a list $somewhere under the report in the URL hierarchy and listed in the staff area so they can be redacted early
2. covered above
3. Hopefully but we should build this out for OSI then get some Reports users to see if the same flow would hold them up when producing Reports' reports
