### ISSUE TITLE
Job Server outages reported by Freshping

### ISSUE THREAD

**Issue by benbc** [opensafely-core/job-server#3812]
Various outages reported from 1400 onwards on Fri 17 Nov.

https://bennettoxford.slack.com/archives/C0270Q313H7/p1700229723418319

**Comment by madwort** [comment]
This was due to a change of network settings on the database cluster. 

The database cluster allows access to a whitelist of “trusted sources”, these were:
* dokku3 reserved ip
* dokku4 reserved ip
* all droplets with the db-access tag
  * dokku3 & dokku4 have this tag


We wanted to block access to this cluster from dokku3, so I removed the dokku3 ip  & the tag, leaving just the dokku4 reserved ip. Apparently dokku4 then couldn’t connect! I just added dokku4's regular ip and it seems to be back online.

The droplets have 3 ips - the regular one which is auto-assigned when creating the droplet, the internal network one & the reserved one which persists from droplet to droplet.

This caused an outage of about 10mins.
