### ISSUE TITLE
Proposal: migrate job-server repository to use Docker Compose v2

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3993]
We currently call `docker-compose` throughout job-server. This is the v1 syntax. [v1 is end-of-life as of June 2023](https://docs.docker.com/compose/release-notes/). v2 has been the default in Docker Desktop for some time, although it does have the feature of aliasing `docker-compose` to `docker compose`.

There are newer features in v2 that are perhaps nice to have, such as [`watch` for rebuilding containers on code changes]( https://docs.docker.com/compose/file-watch/).

Should we specify a minimum version of Docker Compose? (We currently don't.) Should we migrate to the `docker compose` command invocation? 

There's probably not much work involved; it's more the decision making that's the more time consuming aspect here.

Question: are there other repositories using `docker-compose` syntax. Does this actually need to be an organisation wide move?

**Comment by ghickman** [comment]
Related from airlock: https://github.com/opensafely-core/airlock/pull/35

**Comment by bloodearnest** [comment]
Some context here:

 - v2 was not available on `main` in 20.04 until recently (maybe 3 months ago).
 - v2 is not available on EMIS at all, as we cannot upgrade docker.
 
 That led us to standardising on v1.
 
However, job-server is not bound by any of those limitations, being 22.04 based and not a backend.  v1 and v2 are similar enough (the [most visible difference](https://docs.docker.com/compose/migrate/) is using `-` rather than `_` in artifact names) that having some projects use v1 and other v2 is probably not that much of a problem.

**Comment by lucyb** [comment]
I'm moving this to Later, since this isn't urgent and we're starting on a new (and unrelated) initiative.

**Comment by StevenMaude** [comment]
Closing in favour of the duplicate #4364 since we have to switch to keep CI running.
