### ISSUE TITLE
Require DAA 

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#672]
We want all Users to have agreed to the principles of the platform, including collaborators, so we're going to take them through an interstitial page.  We can do this with some middleware to check a boolean on the User object, kicking them off to the relevant page with `?next=<original URL>`.

Name and text to be confirmed by Amir.

**Comment by sebbacon** [comment]
To consider:

* I don't think it's resolved if it should be once-ever, every time, or something else. Amir's suggestion was once per project but there was a concern this would be unecessarily faffy code-wise. We could also consider once every user session.
* We need to avoid click-wrap anti-patterns. This should be a very concise and clear message, and preferably something following the "type the project name" /  "type 'I understand'" paradigm to encourage actual reading
* I'd like to confirm one last time that this isn't a formal, contractual DAA with Amir. Because if it is, we may as well just go through the whole master approvals system rather than allow a separate log-in-via-link system. And if it isn't, I just want to be crystal clear about that, and whose responsibility it is if someone does share something they shouldn't (presumably the person who generated the link?)

**Comment by ghickman** [comment]
Closing this in favour of further requirements collection during the upcoming onboarding voyage and because we switched to requiring all job-server users have been through an onboarding process.

**Comment by sebbacon** [comment]
> we switched to requiring all job-server users have been through an onboarding process

IIRC the point here was that collaborators in the sense of "people who want to review released-&-output-checked-but-not-reviewed-or-approved-for-final-publication outputs" need to agree not to download stuff and email it around?

It's important not to forget this point, how can we be sure to include it as something we definitely consider in the voyage?

**Comment by ghickman** [comment]
That's where collaborators started but then we decided to run them through the current onboarding process.

I'll make a note in the voyage doc.
