### ISSUE TITLE
Can We Speed Up Deploys?

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#854]
Deploys currently take 8-9 minutes, with the longest actions being `assets` (~1m5s), `tests` (~1m30), and `deploy` (~3m).

Some things to look at:
* `assets` is building the asset bundle for `tests`, could that happen alongside `assets`?
* deploys spend ~1m waiting for the container to accept traffic, that seems rather slow?
* ~has caching on GHA, specifically when the cache breaks, improved since we last tried it?~

**Comment by madwort** [comment]
My thoughts on GHA caching, mostly rehashed from the last time this came up, but just for ref. We were holding the caching tool weirdly, conventional use is that *every* job is this shape, with the cache functioning as a cache (that is - it reverts to the next layer of storage on cache miss):
```
- job
  - dependency cache action (read and/or write)
  - dependency installer
  - do the job
```
Whereas we were treating the cache as a reliable file store (which it is not):
```
- job 1
  - dependency installer
  - dependency cache action (write only)
- job 2..n
  - dependency cache action (read only)
  - do the job
```
I don't see how we can use cacheing reliably whilst trying to use it in this way, and I don't expect that to change in GHA.

In the discussions at the time, I understood that our typical pip install into a virtualenv is *not* an idempotent action - that is, if we load the cache & re-run pip install, it will ignore the cache and reinstall everything, saving us no time. So, we apparently can't just do the obvious thing. So, I think possibilities are:

* don't use virtualenv inside GHA - this was ruled out at the time because of "system" python packages. However, I think this is the typical solution used in the wider community, and I have a suspicion that the idea that this is a problem is based on people's use of python on shared systems rather than inside fresh VMs as we have here. 
* use [steps.cache.outputs.cache-hit](https://github.com/actions/cache#Skipping-steps-based-on-cache-hit) to allow us to keep a conditional `dependency installer` action in every job
* there's also an config option in the cache action to fallback to a different key on a cache miss - but without a dependency installer also running in that job we'll probably end  up running CI against the wrong versions of dependencies

One open question is - my assumption is that the failures were due to cache misses, it may be possible that they were due to corrupted or partial caches. The logs have now gone, so I can't verify this either way. With other dependency tools (npm, gem, I suspect pip outside virtualenv) a partial cache would still be useful, but as mentioned above a partial cache is not useful to pip inside virtualenv.

**Comment by madwort** [comment]
[deploy timeouts can be easily tweaked](https://dokku.com/docs/deployment/zero-downtime-deploys/#configuring-check-settings-using-the-config-plugin)

**Comment by ghickman** [comment]
> My thoughts on GHA caching

It's really useful to have all this written out, thank you 👍

> deploy timeouts can be easily tweaked

Yes, I've already bumped it once, but 60s to boot a container seemed quite a lot?

**Comment by madwort** [comment]
final note - if we figure out cacheing/venv etc, we should roll out best practice everywhere - rough-and-ready headcount of the current state (should be verified when someone takes on this task):

* venv, cache - opencodelists
* venv, no cache - job-server, cohort-extractor, 
* bare, no cache - datalabsupport, ebm-sysadmin, ebmbot, euctr-tracker-code, job-runner, matching, openprescribing, opensafely-cli, opensafely/documentation, retractobot, thedatalab

**Comment by ghickman** [comment]
Some idle Sunday morning thoughts:

> our typical pip install into a virtualenv is not an idempotent action

I can't remember why we thought this but I don't think this _should_ be the reason.  I wonder if this was a path issue with pip trying to naively install to a new venv 🤔

**Comment by madwort** [comment]
> > our typical pip install into a virtualenv is not an idempotent action
> 
> I can't remember why we thought this but I don't think this _should_ be the reason. I wonder if this was a path issue with pip trying to naively install to a new venv 🤔

Hmm, yeah, I thought we'd discussed this & there was some reason, but I don't remember exactly & a search of the Slack history turns up nothing. In my head it was @bloodearnest that told me this, but \shrug/ ?  

> > we should roll out best practice everywhere
> 
> Agreed… but with caveats 😁 we have a broad enough selection of projects that I'd expect documenting a working example of caching rather than blanket application to be the most useful solution here.

heh, yeah,  I'm assuming that a random developer will copy-paste from whichever repo they've recently seen working without thinking about it too much, so I'm happy to set the bar at /most/ of the /most common/ repos doing /mostly/ best practice... Citation https://ebmdatalab.slack.com/archives/C63UXGB8E/p1618826328133500

**Comment by madwort** [comment]
simon says ["venvs are not portable"](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1630499778111300?thread_ts=1630495967.109200&cid=C63UXGB8E)

**Comment by madwort** [comment]
this is the way: https://github.com/actions/cache/blob/main/examples.md#python---pip

**Comment by madwort** [comment]
also, we should be able to remove venv - because [the base ubuntu image does not include python](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1630500915118000?thread_ts=1630495967.109200&cid=C63UXGB8E) and [we're using the setup-python action](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1630500771117400?thread_ts=1630495967.109200&cid=C63UXGB8E)

**Comment by ghickman** [comment]
We're now using cache action, via the expected method, as part of setup-python.

**Comment by ghickman** [comment]
I suspect we can still do more here but the work done in #2150 has shaved a couple of minutes off the deploy action (roughly 2x speed increase, measured very unscientifically) 🚀

I'm not sure we'll gain much from improving this any further currently.
